### ISSUE TITLE
Unclear "code reviews waiting for reviewer/submitter" strings

### ISSUE THREAD

**Issue by aklapper** [Bitergia/grimoire-dashboard#1]
In https://github.com/Bitergia/grimoire-dashboard/blob/master/templates/scr/overview.tmpl#L79:L82 are the strings "code reviews waiting for reviewer" and "code reviews waiting for submitter".

I'm forwarding Nemo_bis' comments (a bit rephrased) from https://phabricator.wikimedia.org/T55485#567224 as these are upstream strings:

* "code reviews waiting for reviewer" doesn't make sense, as a code review itself (composed by comments and a judgement like good-to-go or not) by definition always has a reviewer who performed the review. Perhaps this means "changesets / commits / proposed changes (pick one) waiting for reviews", but not sure.
* "code reviews waiting for submitter" presumably means "changesets / commits / proposed changes (pick one) waiting for merge"?

**Comment by jgbarah** [comment]
Probably the trouble is with names, since there are different names being in use in different projects. The naming we used for this based on:

* Code review: the whole "code review cycle", which is a process.
* In each code review, several proposed changes can be proposed, until one of the is merged (and the code review process ends) or until it is abandoned (and the code review process ends as well).
* During each code review process, some times the process needs reviewer actions to move forward, some others it needs submitter actions. In the first case, the "code review process" is waiting for reviewers to act. In the second case the "code review process" is waiting for submitter to act.

For example, when a code review process starts, by submission of a proposed change, in a sense the process is "waiting for reviewer", since it will not move forward until reviewers +1 or -1 it. If the proposed change gets a -1, the process starts to "wait for submitter", since the next required action for the process to "move" is a new submission of another proposed change (or a new version of it, depending on how you call it).

This allows to have some idea of why a code review process is lasting so long: which part of the delay is "due to reviewers", and which part is "due to submitters". Of course, the numbers are not definite, since other reasons and other cases may arise, but it can be an starting point for discussion.

I don't know if the rationale for the names became more clear. If that the case, and you still consider them inappropriate, we can start a discussion on how to better name them. But names should capture the above situation better than current names.

**Comment by aklapper** [comment]
I see. Thanks for elaborating. I think except for "Proposed code changes" I cannot come up with a better word than "Code Review" and it's likely too long and might create problems to describe other situations in that cycle/process. So I'm closing this task.
